FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /src

# Копируем проект
COPY *.sln .
COPY CrmCore/*.csproj CrmCore/

RUN dotnet restore

# Копируем остальные файлы
COPY . .

EXPOSE 8080
EXPOSE 8081

CMD ["dotnet", "watch", "run", "--project", "CrmCore/CrmCore.csproj", "--urls=http://0.0.0.0:8080", "--non-interactive"]
